/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScamsRouteImport } from './routes/scams'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as HelpDoorRouteImport } from './routes/help.$door'
import { Route as HelpLeafLeafIdRouteImport } from './routes/help.leaf.$leafId'

const ScamsRoute = ScamsRouteImport.update({
  id: '/scams',
  path: '/scams',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDoorRoute = HelpDoorRouteImport.update({
  id: '/help/$door',
  path: '/help/$door',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpLeafLeafIdRoute = HelpLeafLeafIdRouteImport.update({
  id: '/help/leaf/$leafId',
  path: '/help/leaf/$leafId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/scams': typeof ScamsRoute
  '/help/$door': typeof HelpDoorRoute
  '/help/': typeof HelpIndexRoute
  '/help/leaf/$leafId': typeof HelpLeafLeafIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/scams': typeof ScamsRoute
  '/help/$door': typeof HelpDoorRoute
  '/help': typeof HelpIndexRoute
  '/help/leaf/$leafId': typeof HelpLeafLeafIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/scams': typeof ScamsRoute
  '/help/$door': typeof HelpDoorRoute
  '/help/': typeof HelpIndexRoute
  '/help/leaf/$leafId': typeof HelpLeafLeafIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-it-works'
    | '/scams'
    | '/help/$door'
    | '/help/'
    | '/help/leaf/$leafId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/scams'
    | '/help/$door'
    | '/help'
    | '/help/leaf/$leafId'
  id:
    | '__root__'
    | '/'
    | '/how-it-works'
    | '/scams'
    | '/help/$door'
    | '/help/'
    | '/help/leaf/$leafId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ScamsRoute: typeof ScamsRoute
  HelpDoorRoute: typeof HelpDoorRoute
  HelpIndexRoute: typeof HelpIndexRoute
  HelpLeafLeafIdRoute: typeof HelpLeafLeafIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scams': {
      id: '/scams'
      path: '/scams'
      fullPath: '/scams'
      preLoaderRoute: typeof ScamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$door': {
      id: '/help/$door'
      path: '/help/$door'
      fullPath: '/help/$door'
      preLoaderRoute: typeof HelpDoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/leaf/$leafId': {
      id: '/help/leaf/$leafId'
      path: '/help/leaf/$leafId'
      fullPath: '/help/leaf/$leafId'
      preLoaderRoute: typeof HelpLeafLeafIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowItWorksRoute: HowItWorksRoute,
  ScamsRoute: ScamsRoute,
  HelpDoorRoute: HelpDoorRoute,
  HelpIndexRoute: HelpIndexRoute,
  HelpLeafLeafIdRoute: HelpLeafLeafIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
