/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AdvocateRouteImport } from './routes/advocate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScamsIndexRouteImport } from './routes/scams.index'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as ScamsScamIdRouteImport } from './routes/scams.$scamId'
import { Route as HelpDoorRouteImport } from './routes/help.$door'
import { Route as HelpLeafLeafIdRouteImport } from './routes/help.leaf.$leafId'

const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvocateRoute = AdvocateRouteImport.update({
  id: '/advocate',
  path: '/advocate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamsIndexRoute = ScamsIndexRouteImport.update({
  id: '/scams/',
  path: '/scams/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamsScamIdRoute = ScamsScamIdRouteImport.update({
  id: '/scams/$scamId',
  path: '/scams/$scamId',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDoorRoute = HelpDoorRouteImport.update({
  id: '/help/$door',
  path: '/help/$door',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpLeafLeafIdRoute = HelpLeafLeafIdRouteImport.update({
  id: '/help/leaf/$leafId',
  path: '/help/leaf/$leafId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advocate': typeof AdvocateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/help/$door': typeof HelpDoorRoute
  '/scams/$scamId': typeof ScamsScamIdRoute
  '/help/': typeof HelpIndexRoute
  '/scams/': typeof ScamsIndexRoute
  '/help/leaf/$leafId': typeof HelpLeafLeafIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advocate': typeof AdvocateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/help/$door': typeof HelpDoorRoute
  '/scams/$scamId': typeof ScamsScamIdRoute
  '/help': typeof HelpIndexRoute
  '/scams': typeof ScamsIndexRoute
  '/help/leaf/$leafId': typeof HelpLeafLeafIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advocate': typeof AdvocateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/help/$door': typeof HelpDoorRoute
  '/scams/$scamId': typeof ScamsScamIdRoute
  '/help/': typeof HelpIndexRoute
  '/scams/': typeof ScamsIndexRoute
  '/help/leaf/$leafId': typeof HelpLeafLeafIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advocate'
    | '/how-it-works'
    | '/help/$door'
    | '/scams/$scamId'
    | '/help/'
    | '/scams/'
    | '/help/leaf/$leafId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advocate'
    | '/how-it-works'
    | '/help/$door'
    | '/scams/$scamId'
    | '/help'
    | '/scams'
    | '/help/leaf/$leafId'
  id:
    | '__root__'
    | '/'
    | '/advocate'
    | '/how-it-works'
    | '/help/$door'
    | '/scams/$scamId'
    | '/help/'
    | '/scams/'
    | '/help/leaf/$leafId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvocateRoute: typeof AdvocateRoute
  HowItWorksRoute: typeof HowItWorksRoute
  HelpDoorRoute: typeof HelpDoorRoute
  ScamsScamIdRoute: typeof ScamsScamIdRoute
  HelpIndexRoute: typeof HelpIndexRoute
  ScamsIndexRoute: typeof ScamsIndexRoute
  HelpLeafLeafIdRoute: typeof HelpLeafLeafIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advocate': {
      id: '/advocate'
      path: '/advocate'
      fullPath: '/advocate'
      preLoaderRoute: typeof AdvocateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scams/': {
      id: '/scams/'
      path: '/scams'
      fullPath: '/scams/'
      preLoaderRoute: typeof ScamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scams/$scamId': {
      id: '/scams/$scamId'
      path: '/scams/$scamId'
      fullPath: '/scams/$scamId'
      preLoaderRoute: typeof ScamsScamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$door': {
      id: '/help/$door'
      path: '/help/$door'
      fullPath: '/help/$door'
      preLoaderRoute: typeof HelpDoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/leaf/$leafId': {
      id: '/help/leaf/$leafId'
      path: '/help/leaf/$leafId'
      fullPath: '/help/leaf/$leafId'
      preLoaderRoute: typeof HelpLeafLeafIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvocateRoute: AdvocateRoute,
  HowItWorksRoute: HowItWorksRoute,
  HelpDoorRoute: HelpDoorRoute,
  ScamsScamIdRoute: ScamsScamIdRoute,
  HelpIndexRoute: HelpIndexRoute,
  ScamsIndexRoute: ScamsIndexRoute,
  HelpLeafLeafIdRoute: HelpLeafLeafIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
